language: julia
os:
  - linux
  - osx
julia:
  - 1.7
  - nightly
matrix:
  allow_failures:
    - julia: nightly
branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags for Documenter.jl, see # 298
    - /^release-.*$/
