name = "GRPF"
uuid = "a0859a10-ccb4-11e8-145d-674b3750773a"
authors = ["Forrest Gasdia <EP-Guy@users.noreply.github.com>"]
version = "1.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
VoronoiDelaunay = "72f80fcb-8c52-57d9-aff0-40c1a3526986"

[compat]
julia = "1.4"
VoronoiDelaunay = "0.4.0"

[extras]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SpecialFunctions", "Test"]
