name = "RootsAndPoles"
uuid = "a0859a10-ccb4-11e8-145d-674b3750773a"
authors = ["Forrest Gasdia <EP-Guy@users.noreply.github.com>"]
version = "2.0.0"

[deps]
DelaunayTriangulation = "927a84f5-c5f4-47a5-9785-b46e178433df"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.7"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
benchmark = ["BenchmarkTools", "LinearAlgebra"]
test = ["SpecialFunctions", "Test"]
